# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:

  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: FortifyScanCentralDAST@7
  inputs:
      scanCentralDastApiUrl: 'http://192.168.213.150:5001/api'
      scanCentralCiCdToken: 'abd8a0d8-5510-427f-a3da-69a22320c3de'
      sscCiToken: 'b5b3591f-d614-4de3-8b07-a3baed35cd07'
